In [1]:
import pandas as pd
import tkinter as tk
import tkinter.ttk as ttk
import tkinter.font as font

print('Import Complete')

Import Complete

In [2]:
filepath = r'C:\Users\pradi\Documents\Sekolah\Artificial Intellingence\Belajar dan dokumentasi\GUI_Training\Obesity_GUI\ObesityDataSet.csv'

data = pd.read_csv(filepath)

In [3]:
data.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [5]:
data.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [6]:
data.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

# GUI

In [20]:
root = tk.Tk()
root.title('Obesity Clustering')
root.attributes('-fullscreen', True)

title_style = font.Font(family='Segoe UI', size = 30)
body_style = font.Font(family='Segoe UI', size = 15)

header = tk.Frame(root, bg='blue', height=20)
header.pack(side=tk.TOP, fill=tk.X)

header_title = tk.Label(header, text='Obesity Clustering', font=title_style, bg='blue', fg='white')
header_title.pack(side=tk.LEFT, padx=15)

sidebar = tk.Frame(root, bg='light blue', width=15)
sidebar.pack(side=tk.LEFT, fill=tk.Y)

main_frame = tk.Frame(root)
main_frame.pack(side=tk.TOP, fill=tk.BOTH, expand=True)



def clear_frame():
    for widgets in main_frame.winfo_children():
        widgets.destroy()

def restore_button():
    children = sidebar.winfo_children()

    for child in children[:-1]:
        child.config(bg='light blue', fg='black')

def title(Text):
    Title = tk.Label(main_frame, text=Text, font=title_style)
    Title.place(relx=.5, rely=.5, anchor=tk.CENTER)

def body(Text):
    Body = tk.Label(main_frame, text=Text, font=body_style, justify='left')
    Body.pack(side=tk.TOP, pady=10, padx=15, anchor='w')

def next(command):
    next_button = tk.Button(main_frame, text='Next Page', command=command, width=15)
    next_button.pack(side=tk.BOTTOM,anchor='s' ,pady=(0,10))

def prev(command):
    prev_button = tk.Button(main_frame, text='Previous Page', command=command, width=15)
    prev_button.pack(side=tk.BOTTOM,anchor='s' ,pady=(0,10))

def button_placeholder():
    placeholder = tk.Label(main_frame)
    placeholder.pack(side=tk.BOTTOM, anchor='s', pady=7)

def pic(image):
    picture = tk.Label(main_frame, image=image)
    picture.pack(side=tk.TOP, pady=(0,10) ,padx=15)

def page_num(num):
    page = tk.Label(main_frame, text=f'Page {num}', font=body_style)
    page.place(relx=.950, rely=.975, anchor='s')


#Importing each image that has been imported
data_head1 = tk.PhotoImage(file='data_head1.png').subsample(2,2)
data_head2 = tk.PhotoImage(file='data_head2.png')
info = tk.PhotoImage(file='info.png').subsample(2,2)


def prep():
    clear_frame()
    restore_button()
    prep_button.config(bg='blue', fg='white')

    def head_page():
        clear_frame()
        page_num('1/4')
        title('Act I: Preparation')
        next(first_page)

    def first_page():
        clear_frame()
        page_num('2/4')
        next(second_page)
        prev(head_page)
        body('Taking a look at the head of the data')
        pic(data_head1)
        pic(data_head2)
        body('As we can see, This dataset consists of mostly  numeric data, and some categorical data that we can convert to numeric \nbut first, lets check the data types')
    def second_page():
        clear_frame()
        page_num('3/4')
        next(third_page)
        prev(first_page)
        pic(info)
        body('We can see that some of the data is still object, we will convert that into numeric so we can use them in the modelling')
    def third_page():
        clear_frame()
        page_num('4/4')
        button_placeholder()
        prev(second_page)
        body('Anjayani3')

    head_page()

def prepro():
    clear_frame()
    restore_button()
    prepro_button.config(bg='blue', fg='white')

    def head_page():
        clear_frame()
        page_num('1/4')
        titles = tk.Label(main_frame, text='Act I: Preparation', font=title_style)
        titles.place(relx=.5, rely=.5, anchor=tk.CENTER)
        next(first_page)

    def first_page():
        clear_frame()
        page_num('1/3')
        title('Preprocessing')
        next(second_page)
        button_placeholder()
        body('Anjayani')
    def second_page():
        clear_frame()
        page_num('2/3')
        title('Preprocessing')
        next(third_page)
        prev(first_page)
        body('Anjayani2')
    def third_page():
        clear_frame()
        page_num('3/3')
        title('Preprocessing')
        button_placeholder()
        prev(second_page)
        body('Anjayani3')

    first_page()

def model():
    clear_frame()
    restore_button()
    model_button.config(bg='blue', fg='white')

    def first_page():
        clear_frame()
        page_num('1/3')
        title('Model')
        next(second_page)
        button_placeholder()
        body('Anjayani')
    def second_page():
        clear_frame()
        page_num('2/3')
        title('Model')
        next(third_page)
        prev(first_page)
        body('Anjayani2')
    def third_page():
        clear_frame()
        page_num('3/3')
        title('Model')
        button_placeholder()
        prev(second_page)
        body('Anjayani3')

    first_page()

def test():
    clear_frame()
    restore_button()
    test_button.config(bg='blue', fg='white')

    def first_page():
        clear_frame()
        page_num('1/3')
        title('Testing')
        next(second_page)
        button_placeholder()
        body('Anjayani')
    def second_page():
        clear_frame()
        page_num('2/3')
        title('Testing')
        next(third_page)
        prev(first_page)
        body('Anjayani2')
    def third_page():
        clear_frame()
        page_num('3/3')
        title('Preparation')
        button_placeholder()
        prev(second_page)
        body('Anjayani3')

    first_page()
        

prep_button = tk.Button(sidebar, text='Preparation', bg='light blue', width=15, bd=0, font=body_style, command=prep)
prep_button.pack(side=tk.TOP, pady=15)

prepro_button = tk.Button(sidebar, text='Preprocessing', bg='light blue', width=15, bd=0, font=body_style, command=prepro)
prepro_button.pack(side=tk.TOP, pady=15)

model_button = tk.Button(sidebar, text='Model', bg='light blue', width=15, bd=0, font=body_style, command=model)
model_button.pack(side=tk.TOP, pady=15)

test_button = tk.Button(sidebar, text='Testing', bg='light blue', width=15, bd=0, font=body_style, command=test)
test_button.pack(side=tk.TOP, pady=15)

exit_button = tk.Button(sidebar, text='EXIT', bg='red',fg='white' ,width=15, bd=0, font=body_style, command=root.destroy)
exit_button.pack(side=tk.BOTTOM, pady=15)

root.mainloop()